### ISSUE TITLE
Single tree is not recognized as such (or wikidata wrong?)

### ISSUE THREAD

**Issue by mcliquid** [matkoniecz/OSM-wikipedia-tag-validator#10]
In Italy, a single tree is marked as an error.
OSM ID (Node): https://www.openstreetmap.org/node/2448408805
Wikidata: https://www.wikidata.org/wiki/Q33040885

I don't know much about wikidata, but the object looks properly captured there. Seems to be a false-positive or? Maybe you can filter that out (if it is wrong)?

**Comment by danieldegroot2** [comment]
Please link to the validator entry when reporting an issue.

> [should use a secondary wikipedia tag - linking to an animal or plant (and not an individual one)](https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/Italia%20(Italy,%20W%C5%82ochy).html#should%20use%20a%20secondary%20wikipedia%20tag%20-%20linking%20to%20an%20animal%20or%20plant%20(and%20not%20an%20individual%20one))

> linked wikidata entry (Q33040885) is about an animal or plant (and not an individual one), so it is very unlikely to be correct
subject:wikipedia=* tag would be probably better (see https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_Wikipedia_links for full list of what else may be applicable)
in case of change remember to remove wikidata tag if it is present
object categorised by Wikidata - wrong classification may be caused by wrong data on Wikidata
[Vecchio Tiglio - an affected OSM element that may be improved](https://openstreetmap.org/node/2448408805)

> [overpass query](https://overpass-turbo.eu/) usable in JOSM that will load all objects where this specific error is present:
[out:xml][timeout:3600]; ( node(2448408805)['wikidata'='Q33040885']; ); (._;>;); out meta qt;//['should use a secondary wikipedia tag - linking to an animal or plant (and not an individual one)']

**Comment by danieldegroot2** [comment]
Example link for this specific issue:
https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/Italia%20(Italy,%20W%C5%82ochy).html#should%20use%20a%20secondary%20wikipedia%20tag%20-%20linking%20to%20an%20animal%20or%20plant%20(and%20not%20an%20individual%20one)

This link brings someone to the section which has the error you are describing.

Mateusz should eventually reply. It does seem to be a false positive though.

**Comment by matkoniecz** [comment]
I need to look at it what went wrong  - maybe wikidata data was recently fixed

Oh, and at least for me link to osm object is good though to look at the database entry

**Comment by matkoniecz** [comment]
seems to be case of cached invalid wikidata entry (see https://www.wikidata.org/w/index.php?title=Q33040885&action=history )

added test to prevent regression, will not be listed once data updates
